# Define the columns to drop and the categorical columns
COLS_TO_DROP = [
    "LotFrontage",
    "Alley",
    "MasVnrType",
    "MasVnrArea",
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2",
    "Electrical",
    "FireplaceQu",
    "GarageType",
    "GarageYrBlt",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
    "PoolQC",
    "Fence",
    "MiscFeature",
]  # Define your columns to drop here

COLS_TO_CAST = ["MSSubClass", "OverallCond", "YrSold", "MoSold"]

CAT_COLS = [
    "ExterQual",
    "ExterCond",
    "HeatingQC",
    "KitchenQual",
    "Functional",
    "LandSlope",
    "LotShape",
    "PavedDrive",
    "Street",
    "CentralAir",
    "MSSubClass",
    "OverallCond",
    "YrSold",
    "MoSold",
    "MSZoning",
    "LandContour",
    "Utilities",
    "LotConfig",
    "Neighborhood",
    "Condition1",
    "Condition2",
    "BldgType",
    "HouseStyle",
    "RoofStyle",
    "RoofMatl",
    "Exterior1st",
    "Exterior2nd",
    "Foundation",
    "Heating",
    "SaleType",
    "SaleCondition",
]

SAMPLE_DATA = {
    "MSSubClass": 20,
    "MSZoning": "RH",
    "LotFrontage": 80.0,
    "LotArea": 11622,
    "Street": "Pave",
    "Alley": None,
    "LotShape": "Reg",
    "LandContour": "Lvl",
    "Utilities": "AllPub",
    "LotConfig": "Inside",
    "LandSlope": "Gtl",
    "Neighborhood": "NAmes",
    "Condition1": "Feedr",
    "Condition2": "Norm",
    "BldgType": "1Fam",
    "HouseStyle": "1Story",
    "OverallQual": 5,
    "OverallCond": 6,
    "YearBuilt": 1961,
    "YearRemodAdd": 1961,
    "RoofStyle": "Gable",
    "RoofMatl": "CompShg",
    "Exterior1st": "VinylSd",
    "Exterior2nd": "VinylSd",
    "MasVnrType": None,
    "MasVnrArea": 0.0,
    "ExterQual": "TA",
    "ExterCond": "TA",
    "Foundation": "CBlock",
    "BsmtQual": "TA",
    "BsmtCond": "TA",
    "BsmtExposure": "No",
    "BsmtFinType1": "Rec",
    "BsmtFinSF1": 468.0,
    "BsmtFinType2": "LwQ",
    "BsmtFinSF2": 144.0,
    "BsmtUnfSF": 270.0,
    "TotalBsmtSF": 882.0,
    "Heating": "GasA",
    "HeatingQC": "TA",
    "CentralAir": "Y",
    "FirstFlrSF": 896,
    "SecondFlrSF": 0,
    "LowQualFinSF": 0,
    "GrLivArea": 896,
    "BsmtFullBath": 0.0,
    "BsmtHalfBath": 0.0,
    "FullBath": 1,
    "HalfBath": 0,
    "BedroomAbvGr": 2,
    "KitchenAbvGr": 1,
    "KitchenQual": "TA",
    "TotRmsAbvGrd": 5,
    "Functional": "Typ",
    "Fireplaces": 0,
    "FireplaceQu": None,
    "GarageType": "Attchd",
    "GarageYrBlt": 1961.0,
    "GarageFinish": "Unf",
    "GarageCars": 1.0,
    "GarageArea": 730.0,
    "GarageQual": "TA",
    "GarageCond": "TA",
    "PavedDrive": "Y",
    "WoodDeckSF": 140,
    "OpenPorchSF": 0,
    "EnclosedPorch": 0,
    "ThreeSsnPorch": 0,
    "ScreenPorch": 120,
    "PoolArea": 0,
    "PoolQC": None,
    "Fence": "MnPrv",
    "MiscFeature": None,
    "MiscVal": 0,
    "MoSold": 6,
    "YrSold": 2010,
    "SaleType": "WD",
    "SaleCondition": "Normal",
}
